[metadata]
name = PyPress
version = 1.0.4
author = D4vel0per
author_email = odm2.letter@gmail.com
description = A package to create your python HTTP server with no effort
long_description = file: README.md, LICENSE.txt
long_description_content_type = text/markdown
url = https://github.com/D4vel0per/pypress
project_urls =
    Bug Tracker = https://github.com/D4vel0per/pypress/issues
    repository = https://github.com/D4vel0per/pypress
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.11
install_requires =
    pydantic
    pymongo
    requests

[options.packages.find]
where = src